name: bhtrace
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - uniplot
  - jupyter
  - pytorch
  - tqdm
  - scipy
  - sympy
  - httpx
  - hydra-core