name: bhtrace_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - uniplot
  - jupyter
  - pytorch-cpu
  - tqdm
  - scipy
  - sympy
  - httpx